name: 2048 Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: change directory
        run: cd 2048
      - name: install modules
        run: npm install
      - name: build project
        run: npm build
          