name: My React Workflow Excersize
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install modules
        uses: actions/checkout@v2
      - run: npm install
